### ISSUE TITLE
Intellisense - Can't select suggestion

### ISSUE THREAD

**Issue by thnk2wn** [MrJul/ForTea#51] opened 2015-04-27 20:14 UTC
When I select something from the intellisense list using Enter or Tab, what I selected doesn't get inserted. Instead just "_()". See https://www.dropbox.com/s/fova73g3jxr44ls/2015-04-27_13-09-28.mp4?dl=0

Also can't type "." with something selected. I always have to hit Escape after the suggestions come up.

It seems to sort of work for the left hand side of expressions when there's no code before it but anything on right hand side is effected.

Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Resharper 9.1
ForTea 1.3.2

**Comment by MrJul** [comment] 2015-04-27 21:03
Does it happen only for this file? For a particular type?
I can't seem to reproduce, a simple repro would be grealy appreciated!

**Comment by thnk2wn** [comment] 2015-04-27 21:38
See https://www.dropbox.com/s/xe0l18ug5fzm09r/Cyrus.CodeGen.zip?dl=0

Open SprocReader.ttinclude. You can repro with a method like GetResultSetInfo by wiping out the right side an assignment where it uses the DataReader.

**Comment by MrJul** [comment] 2015-04-27 21:55
Thank you! At fist I couldn't reproduce. After messing with the options, it turns out completion fails only if "show members signatures" is disabled in Environment | IntelliSense | Completion Appearance. (As a temporary workaround, you can try to enable it.)

**Comment by thnk2wn** [comment] 2015-04-27 22:04
Ahh, thanks. Changing that R# option is a good workaround until that can be supported.

**Comment by MrJul** [comment] 2015-04-27 22:20
I found the root cause: removing the include directive from SqlServerNewSelectSproc.tt and restarting VS solves the problem, as odd as it sounds. I will investigate further.

**Comment by ac4simms** [comment] 2015-08-24 17:07
I have the same problem in all files.

http://screencast.com/t/FdvB4nhM

**Comment by MrJul** [comment] 2015-09-15 18:59
Okay, I was investigating this issue tonight and found the root cause, related to include files. Unfortunately, I'm not sure if I can work around it or if it needs some fix inside ReSharper.

@citizenmatt @derigel23 I believe I need your help here. When a T4 file is parsed, I call `FileDependency.UpdateDependencies` inside `SecondaryDocumentGenerationResult.CommitChanges` to invalidate any file that has included the current file, exactly like `HtmlSecondaryDocumentGenerationResult` does.

However, since this method marks the includers (is that a word?) as dirty, completing the current intellisense item then fails with an exception : *All documents should be committed, but these are dirty: &lt;includer file&gt;*. I think that's a ReSharper problem, because I can reproduce the exact same behavior with .aspx files and `<!-- #include -->` directives (see [DEXP-63128](https://youtrack.jetbrains.com/issue/DEXP-63128)). Do you think there's a workaround?

**Closed** 2015-09-16 17:17 UTC
Labels: bug

**Comment by MrJul** [comment] 2015-09-16 17:21
I chose not to use ReSharper's `FileDependency` at all . I rolled my own [T4FileDependencyManager](https://github.com/MrJul/ForTea/blob/master/GammaJul.ReSharper.ForTea/Psi/T4FileDependencyManager.cs) that invalidates and re-commits includers. I don't know if it's the best way to solve the problem, but it works.

Will be in v1.4.0.

**Comment by citizenmatt** [comment] 2015-09-21 09:06
Sorry, been offline for a few days. Sounds like you've hit a bug - have you reported it other than the exception stack? If not, please could you get a quick repro together please, and I'll chase it up.
