### ISSUE TITLE
When using assembly link to dll, imported namespace is marked as an unresolved symbol.

### ISSUE THREAD

**Issue by iyakov** [MrJul/ForTea#69] opened 2016-03-03 11:27 UTC
I use this attributes for my tt file in Unity3D project. tt generates code that is compiled into Assembly-CSharp.dll. Then I use it to import its code.

```
<#@ template debug="true" hostspecific="false" language="C#" #>
<#@ output extension="cs" #>
<#@ assembly name="$(ProjectDir)\Temp\UnityVS_bin\Debug\Assembly-CSharp.dll" #>
<#@ import namespace="MyApp.Common.CodeGeneration" #>

```

It works however when I start VS2015 **next time**, Resharper marks **MyApp** as an **unresolved symbol**!

**Comment by iyakov** [comment] 2016-03-03 11:32
It's possible, it could be the same issue as https://github.com/MrJul/ForTea/issues/50
VS 2015 (14.0.24720.00 Update 1),
Resharper 10.0.2, 
ForTea 1.5.0

**Comment by MrJul** [comment] 2016-05-18 15:00
I'm closing this as a duplicate of #50.

**Closed by MrJul** 2016-05-18 15:00 UTC
