### ISSUE TITLE
assembly imports not recognized.

### ISSUE THREAD

**Issue by Giorgi** [MrJul/ForTea#48] opened 2015-01-26 10:52 UTC
I installed nuget package [EntityFramework.CodeTemplates.CSharp](https://www.nuget.org/packages/EntityFramework.CodeTemplates.CSharp/) which contains t4 templates for Entity Framework code first generation but ForTea is reporting false positives.

It dims all namespaces in `import namespace` statement and consequently `CSharpCodeHelper` and `EdmHelper` are highlighted in red. As a result all code that uses them is marked as error and intellisense does not work neither

Is there anything I can do to get it working?

![image](https://cloud.githubusercontent.com/assets/580749/5898667/0c7b528e-a56b-11e4-8c77-70657796570e.png)

**Comment by aensidhe** [comment] 2015-02-17 14:40
I have same issue and same question. :+1:

**Comment by MrJul** [comment] 2015-02-17 15:51
ForTea cannot resolve the Microsoft.Data.Entity.Design and EntityFramework assemblies since VS cannot either in a standard design T4 file (add TextTemplatingFileGenerator as a custom tool to the .t4 files to reproduce). It seems the EntityFramework generator adds custom paths for assembly resolving before calling the template and ForTea can't know that.

As a work around, please try to add those lines to the file:
```
<#@ assembly name="" completion="$(DevEnvDir)\Microsoft.Data.Entity.Design.dll" #>
<#@ assembly name="" completion="$(DevEnvDir)\EntityFramework.dll" #>
```

**Comment by MrJul** [comment] 2015-04-27 22:26
@Giorgi @aensidhe Is the workaround OK for you?

**Comment by aensidhe** [comment] 2015-04-28 04:55
Thank you, but we dropped our T4 and replaced it with Roslyn. So I didn't try it, sorry.

**Comment by MrJul** [comment] 2015-09-15 19:42
Closing this since there's a workaround. Reopen if needed.

**Closed by MrJul** 2015-09-15 19:42 UTC
