### ISSUE TITLE
ForTea 1.5.0 can't install on Resharper 10.0.2

### ISSUE THREAD

**Issue by wywgong** [MrJul/ForTea#66] opened 2016-01-20 02:11 UTC
Reproduce:
Step 1: Open Extension Manager and search for ForTea,
Step 2: Select install and install the ForTea plugin.
Step 3: A message popup and say the plugin install successful and need to restart the VS2015.
Step 4: After restart the ForTea still show not installed in Extension Manager

Environment: Windows 10, VS2015 with no Update 1, ReSharper 10.0.2

Note: only ForTea plugin has this problem, I install the AngularJS(For Resharper 10) also, and it works

Thanks

**Comment by IanYates** [comment] 2016-01-20 05:30
It's working for me...  I'm on the same build except I do have update 1 for VS 2015 installed.

What shows up in your ReSharper->Help->About...?

JetBrains ReSharper Ultimate 10.0.2 Build 104.0.20151218.120627
ReSharper 10.0.20151218.130009

Application Packages:
CitizenMatt Xunit build 2.3.3 on 2016-01-08 02:28:03Z.
Hunt ResharperGlyphfriend build 0.7.0 on 2016-01-08 02:28:03Z.
JetBrains Platform Core Ide build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Core Shell build 104.0.20151218.120331 on 2015-12-18 12:03:31Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Core Text build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Installer build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Interop dotMemoryUnit.Interop build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Symbols build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform VisualStudio build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Psi.Features Core build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains Psi.Features SolutionBuilder build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains Psi.Features src build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains Psi.Features Tasks build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains Psi.Features UnitTesting build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains Psi.Features VisualStudio build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains ReSharper src build 104.0.20151218.130009 on 2015-12-18 13:00:09Z rev hg::wave04::0CC7974EA67C30AA8DDD61FF7AF47751EA285DAF.
JLebosquain ForTea build 1.5.0 on 2016-01-08 02:28:04Z.
ReSharper HeapView.R100 build 1.1.0 on 2016-01-08 02:28:04Z.

**Comment by wywgong** [comment] 2016-01-20 07:05
@IanYates Thank you for your reply
Here is my info

JetBrains ReSharper Ultimate 10.0.2 Build 104.0.20151218.120627
dotCover 10.0.20151218.125453
dotMemory 10.0.20151218.125655
dotTrace 10.0.20151218.132452
ReSharper C++ 10.0.20151218.122414
ReSharper 10.0.20151218.130009

Application Packages:
JetBrains AngularJS build 1.4.1 on 2016-01-20 02:00:27Z.
JetBrains DotCommon Core build 104.0.20151218.121412 on 2015-12-18 12:14:13Z rev hg::wave04::1E7889921A11F3D09F6ADC2067688F9D374EF5A0.
JetBrains DotCommon ElevationAgent build 104.0.20151218.121412 on 2015-12-18 12:14:13Z rev hg::wave04::1E7889921A11F3D09F6ADC2067688F9D374EF5A0.
JetBrains DotCommon ExternalStorage build 104.0.20151218.121412 on 2015-12-18 12:14:13Z rev hg::wave04::1E7889921A11F3D09F6ADC2067688F9D374EF5A0.
JetBrains DotCommon Native Core build 104.0.20151218.120807 on 2015-12-18 12:08:08Z rev hg::wave04::1E7889921A11F3D09F6ADC2067688F9D374EF5A0.
JetBrains DotCommon Native Libraries build 104.0.20151218.120807 on 2015-12-18 12:08:08Z rev hg::wave04::1E7889921A11F3D09F6ADC2067688F9D374EF5A0.
JetBrains DotCommon Native Link build 104.0.20151218.120807 on 2015-12-18 12:08:08Z rev hg::wave04::1E7889921A11F3D09F6ADC2067688F9D374EF5A0.
JetBrains DotCommon.Psi Navigation build 104.0.20151218.122204 on 2015-12-18 12:22:05Z rev hg::wave04::FEA6648C7B9A620629209F581252BA1D4E586310.
JetBrains DotCommon.Psi UnitTesting build 104.0.20151218.122204 on 2015-12-18 12:22:05Z rev hg::wave04::FEA6648C7B9A620629209F581252BA1D4E586310.
JetBrains DotCommon Remotable build 104.0.20151218.121412 on 2015-12-18 12:14:13Z rev hg::wave04::1E7889921A11F3D09F6ADC2067688F9D374EF5A0.
JetBrains DotCommon Timeline build 104.0.20151218.121412 on 2015-12-18 12:14:13Z rev hg::wave04::1E7889921A11F3D09F6ADC2067688F9D374EF5A0.
JetBrains DotCover Core build 104.0.20151218.125453 on 2015-12-18 12:54:55Z rev hg::wave04::0C8BD113611F280A372F0242F073200BEAC72AE5.
JetBrains DotCover Presentation build 104.0.20151218.125453 on 2015-12-18 12:54:55Z rev hg::wave04::0C8BD113611F280A372F0242F073200BEAC72AE5.
JetBrains DotCover VisualStudio build 104.0.20151218.125453 on 2015-12-18 12:54:55Z rev hg::wave04::0C8BD113611F280A372F0242F073200BEAC72AE5.
JetBrains DotMemory Common build 104.0.20151218.125655 on 2015-12-18 12:56:58Z rev hg::wave04::B1034EE60183ACEB27AD6718767E36F1635ECA7F.
JetBrains DotMemory Core build 104.0.20151218.125655 on 2015-12-18 12:56:58Z rev hg::wave04::B1034EE60183ACEB27AD6718767E36F1635ECA7F.
JetBrains DotMemory VisualStudio build 104.0.20151218.125655 on 2015-12-18 12:56:58Z rev hg::wave04::B1034EE60183ACEB27AD6718767E36F1635ECA7F.
JetBrains DotTrace CommonUI build 104.0.20151218.132452 on 2015-12-18 13:24:54Z rev hg::wave04::3F180330BA20C93FFF302FAC231EA1386594F2E9.
JetBrains DotTrace Core build 104.0.20151218.132452 on 2015-12-18 13:24:54Z rev hg::wave04::3F180330BA20C93FFF302FAC231EA1386594F2E9.
JetBrains DotTrace dotInstant build 104.0.20151218.132452 on 2015-12-18 13:24:54Z rev hg::wave04::3F180330BA20C93FFF302FAC231EA1386594F2E9.
JetBrains DotTrace Snapshot build 104.0.20151218.132452 on 2015-12-18 13:24:54Z rev hg::wave04::3F180330BA20C93FFF302FAC231EA1386594F2E9.
JetBrains DotTrace VisualStudio build 104.0.20151218.132452 on 2015-12-18 13:24:54Z rev hg::wave04::3F180330BA20C93FFF302FAC231EA1386594F2E9.
JetBrains EtwService Core build 104.0.20151218.121333 on 2015-12-18 12:13:34Z rev hg::wave04::F304BE0570EB603E69FC806DC4BACDA33B137703.
JetBrains EtwService msi build 104.0.20151218.123142 on 2015-12-18 12:31:42Z rev hg::wave04::F304BE0570EB603E69FC806DC4BACDA33B137703.
JetBrains EtwService Native Core build 104.0.20151218.123142 on 2015-12-18 12:31:42Z rev hg::wave04::F304BE0570EB603E69FC806DC4BACDA33B137703.
JetBrains EtwService Native Link build 104.0.20151218.123142 on 2015-12-18 12:31:42Z rev hg::wave04::F304BE0570EB603E69FC806DC4BACDA33B137703.
JetBrains Platform Core Ide build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Core Shell build 104.0.20151218.120331 on 2015-12-18 12:03:31Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Core Text build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Installer build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Interop dotMemoryUnit.Interop build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Standalone Shell build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Standalone TabWell build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform Symbols build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Platform VisualStudio build 104.0.20151218.120627 on 2015-12-18 12:06:27Z rev hg::wave04::6641DBD656154A191C5F0AD77BB5929488302078.
JetBrains Profiler Configurator Core build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Configurator WPF build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Editor Core build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Editor Windows BehaviorModel build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Editor Windows WPF build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler History Core build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Kernel CleanUp build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Kernel Core build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Kernel InternalLauncher build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Kernel Windows Api build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Kernel Windows Engine build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Kernel Windows Native Core build 104.0.20151218.120902 on 2015-12-18 12:09:02Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Kernel Windows Native Link build 104.0.20151218.120902 on 2015-12-18 12:09:02Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler Snapshot build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler VsIntegration Core build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Profiler VsIntegration Windows build 104.0.20151218.121932 on 2015-12-18 12:19:33Z rev hg::wave04::2A55A9B8AEC4961EEB7379C6B497360483124ADE.
JetBrains Psi.Features Core build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains Psi.Features Cpp src build 104.0.20151218.122414 on 2015-12-18 12:24:16Z rev hg::wave04::38174FA30F48A10C1445A8DAF98C2BC74708C36E.
JetBrains Psi.Features SolutionBuilder build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains Psi.Features src build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains Psi.Features Tasks build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains Psi.Features UnitTesting build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains Psi.Features VisualStudio build 104.0.20151218.121033 on 2015-12-18 12:10:33Z rev hg::wave04::888E2072B0EDD574E836DD53F9C0E73127F46545.
JetBrains ReSharper src build 104.0.20151218.130009 on 2015-12-18 13:00:09Z rev hg::wave04::0CC7974EA67C30AA8DDD61FF7AF47751EA285DAF.
JetBrains Timeline Src Shared build 104.0.20151218.122430 on 2015-12-18 12:24:30Z rev hg::wave04::2EB2330BFE69BC4232E2699358830C38F3B25377.

dotCover 10.0.2 Licensed to XXX, assigned to XXX
dotTrace 10.0.2 Licensed to XXX, assigned to XXX
ReSharper C++ 10.0.2 Licensed to XXX, assigned to XXX
ReSharper 10.0.2 Licensed to XXX, assigned to XXX
Visual Studio 14.0.23107.0.

Copyright ? 2016 JetBrains. All rights reserved.

**Comment by MrJul** [comment] 2016-05-18 14:59
I can't reproduce either and no further information have been provided. I'm closing this issue. Feel free to re-open if needed.

**Closed by MrJul** 2016-05-18 14:59 UTC
